PREFIXE= .
NOM_OWNER="Szchino"
NUMERO_OWNER="+2250715405077"
MODE=private
MENU=https://i.ibb.co/ynx9QcZ/image.jpg
SESSION_ID="malvin~grMl2L7D#yq3BfRiMs6xa6ytOCNMYH3HzOnLJ95UZkBDyKwgV_lI"
DATABASE=postgresql://postgres.qnjvgxwyncnsbpfxwrbq:ovlmdmdpasse@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
LEVEL_UP="on"
STICKER_PACK_NAME="Sz-sticker"
STICKER_AUTHOR_NAME="OVL-MD"
ANTIDELETE="off/pm/status/gc/all"
RENDER_API_KEY=
DL_STATUS="on"
ANTI_VUE_UNIQUE="on"
LIKE_STATUS="on"
PRESENCE="off/enregistre/ecrit/enligne"
LECTURE_STATUS="on/off"
